"""Fix HocKy ID auto increment

Revision ID: 0c6e7ac084ab
Revises: 5ae6188dffc9
Create Date: 2026-05-02 17:42:15.808970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c6e7ac084ab'
down_revision: Union[str, None] = '5ae6188dffc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
