"""Final cleanup and TKB AI integration

Revision ID: 0e75220aca15
Revises: 593ef93d4162
Create Date: 2026-05-01 17:45:19.147138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e75220aca15'
down_revision: Union[str, None] = '593ef93d4162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
