"""fix sinhvien id identity

Revision ID: 27d279cf158d
Revises: ff0cec144779
Create Date: 2026-05-02 18:46:32.601472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d279cf158d'
down_revision: Union[str, None] = 'ff0cec144779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE sinhvien ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE sinhvien ALTER COLUMN id DROP IDENTITY IF EXISTS")
    # ### end Alembic commands ###
