"""Add administrative fields to sinhvien

Revision ID: 3ade0d0a835f
Revises: 73b928f6fe57
Create Date: 2026-05-02 19:11:01.650525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ade0d0a835f'
down_revision: Union[str, None] = '73b928f6fe57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sinhvien', sa.Column('ma_ho_so', sa.String(), nullable=True))
    op.add_column('sinhvien', sa.Column('noi_sinh', sa.Text(), nullable=True))
    op.add_column('sinhvien', sa.Column('dan_toc', sa.String(), nullable=True))
    op.add_column('sinhvien', sa.Column('ton_giao', sa.String(), nullable=True))
    op.add_column('sinhvien', sa.Column('nguyen_quan', sa.Text(), nullable=True))
    op.add_column('sinhvien', sa.Column('ho_khau', sa.Text(), nullable=True))
    op.add_column('sinhvien', sa.Column('ngay_vao_doan', sa.Date(), nullable=True))
    op.add_column('sinhvien', sa.Column('bac_dao_tao', sa.String(), nullable=True))
    op.add_column('sinhvien', sa.Column('ho_ten_cha', sa.String(), nullable=True))
    op.add_column('sinhvien', sa.Column('nghe_nghiep_cha', sa.String(), nullable=True))
    op.add_column('sinhvien', sa.Column('ho_ten_me', sa.String(), nullable=True))
    op.add_column('sinhvien', sa.Column('nghe_nghiep_me', sa.String(), nullable=True))
    op.add_column('sinhvien', sa.Column('dien_thoai', sa.String(), nullable=True))
    op.add_column('sinhvien', sa.Column('trang_thai', sa.String(), nullable=True))
    op.add_column('sinhvien', sa.Column('ngay_ra_quyet_dinh', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sinhvien', 'ngay_ra_quyet_dinh')
    op.drop_column('sinhvien', 'trang_thai')
    op.drop_column('sinhvien', 'dien_thoai')
    op.drop_column('sinhvien', 'nghe_nghiep_me')
    op.drop_column('sinhvien', 'ho_ten_me')
    op.drop_column('sinhvien', 'nghe_nghiep_cha')
    op.drop_column('sinhvien', 'ho_ten_cha')
    op.drop_column('sinhvien', 'bac_dao_tao')
    op.drop_column('sinhvien', 'ngay_vao_doan')
    op.drop_column('sinhvien', 'ho_khau')
    op.drop_column('sinhvien', 'nguyen_quan')
    op.drop_column('sinhvien', 'ton_giao')
    op.drop_column('sinhvien', 'dan_toc')
    op.drop_column('sinhvien', 'noi_sinh')
    op.drop_column('sinhvien', 'ma_ho_so')
    # ### end Alembic commands ###
