"""khoi_tao_db_chuan_identity

Revision ID: 48159fee6f15
Revises: 
Create Date: 2026-04-07 19:13:40.745514

"""
from typing import Sequence, Union
import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48159fee6f15'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diemdanh', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('face_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=128),
               type_=pgvector.sqlalchemy.Vector(dim=512),
               existing_nullable=False)
    op.alter_column('giangvien', 'auth_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('sinhvien', 'sinhtrachoc',
               existing_type=pgvector.sqlalchemy.Vector(dim=128),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('thoikhoabieu', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('thongbao', 'id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=True),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('thongbao', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tkb_tiet', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tkb_tiet', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('thongbao', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('thongbao', 'id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('thoikhoabieu', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sinhvien', 'sinhtrachoc',
               existing_type=sa.Text(),
               type_=pgvector.sqlalchemy.Vector(dim=128),
               existing_nullable=True)
    op.alter_column('giangvien', 'auth_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('face_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=512),
               type_=pgvector.sqlalchemy.Vector(dim=128),
               existing_nullable=False)
    op.alter_column('diemdanh', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
