"""Add soft delete and audit columns

Revision ID: 4b1795e48e7f
Revises: c3296f6eb9ef
Create Date: 2026-05-02 14:28:09.269818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b1795e48e7f'
down_revision: Union[str, None] = 'c3296f6eb9ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giangvien', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('hocky', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('hocky', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('hocphan', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('hocphan', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('khoa', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('khoa', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('lop', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('lop', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lop', 'deleted_at')
    op.drop_column('lop', 'updated_at')
    op.drop_column('khoa', 'deleted_at')
    op.drop_column('khoa', 'updated_at')
    op.drop_column('hocphan', 'deleted_at')
    op.drop_column('hocphan', 'updated_at')
    op.drop_column('hocky', 'deleted_at')
    op.drop_column('hocky', 'updated_at')
    op.drop_column('giangvien', 'deleted_at')
    # ### end Alembic commands ###
