"""Consolidate schedule into TKB and add AI settings

Revision ID: 593ef93d4162
Revises: c7ef8c92cbc7
Create Date: 2026-05-01 17:01:18.698622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '593ef93d4162'
down_revision: Union[str, None] = 'c7ef8c92cbc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
