"""Add loai_hocky to HocKy

Revision ID: 5ae6188dffc9
Revises: 4b1795e48e7f
Create Date: 2026-05-02 17:33:52.176450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ae6188dffc9'
down_revision: Union[str, None] = '4b1795e48e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hocky', sa.Column('loai_hocky', sa.Text(), server_default='Chính', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hocky', 'loai_hocky')
    # ### end Alembic commands ###
