"""Add week specific scheduling support

Revision ID: 6a5244e54d3d
Revises: 977ab2e38a7d
Create Date: 2026-05-02 18:06:34.091738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a5244e54d3d'
down_revision: Union[str, None] = '977ab2e38a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thoikhoabieu', sa.Column('tuan_hoc_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'thoikhoabieu', 'tuan_hoc', ['tuan_hoc_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thoikhoabieu', type_='foreignkey')
    op.drop_column('thoikhoabieu', 'tuan_hoc_id')
    # ### end Alembic commands ###
