"""Fix HocKy ID auto increment

Revision ID: 977ab2e38a7d
Revises: 0c6e7ac084ab
Create Date: 2026-05-02 17:44:28.474842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '977ab2e38a7d'
down_revision: Union[str, None] = '0c6e7ac084ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Dùng raw SQL để ép kiểu Identity vì alter_column có thể lỗi nếu cột chưa là Identity
    op.execute('ALTER TABLE hocky ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
