"""Add tracking columns and unique constraint to diemdanh

Revision ID: 9f39d0e49b83
Revises: d3a64da5ef0d
Create Date: 2026-04-20 09:42:12.308213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f39d0e49b83'
down_revision: Union[str, None] = 'd3a64da5ef0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diemdanh', sa.Column('device_id', sa.Text(), nullable=True))
    op.add_column('diemdanh', sa.Column('client_version', sa.Text(), nullable=True))
    op.add_column('diemdanh', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('diemdanh', sa.Column('note', sa.Text(), nullable=True))
    op.create_index('idx_diemdanh_ngay', 'diemdanh', ['ngay_diem_danh'], unique=False)
    op.create_index('idx_diemdanh_tkb', 'diemdanh', ['tkb_tiet_id'], unique=False)
    op.create_unique_constraint('uq_diemdanh_sv_tiet_ngay', 'diemdanh', ['sv_id', 'tkb_tiet_id', 'ngay_diem_danh'])
    op.add_column('face_embeddings', sa.Column('model_version', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('face_embeddings', 'model_version')
    op.drop_constraint('uq_diemdanh_sv_tiet_ngay', 'diemdanh', type_='unique')
    op.drop_index('idx_diemdanh_tkb', table_name='diemdanh')
    op.drop_index('idx_diemdanh_ngay', table_name='diemdanh')
    op.drop_column('diemdanh', 'note')
    op.drop_column('diemdanh', 'confidence_score')
    op.drop_column('diemdanh', 'client_version')
    op.drop_column('diemdanh', 'device_id')
    # ### end Alembic commands ###
