"""Add email to khoa and teacher to schedules

Revision ID: b02158e989a0
Revises: b6ee90947309
Create Date: 2026-05-01 16:54:51.883803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b02158e989a0'
down_revision: Union[str, None] = 'b6ee90947309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_schedules', sa.Column('giangvien_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attendance_schedules', 'giangvien', ['giangvien_id'], ['id'])
    op.add_column('khoa', sa.Column('email', sa.String(), nullable=True))
    op.drop_index(op.f('ix_khoa_code'), table_name='khoa')
    op.drop_column('khoa', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('khoa', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_khoa_code'), 'khoa', ['code'], unique=True)
    op.drop_column('khoa', 'email')
    op.drop_constraint(None, 'attendance_schedules', type_='foreignkey')
    op.drop_column('attendance_schedules', 'giangvien_id')
    # ### end Alembic commands ###
