"""Add so_tuan_hoc to Semester

Revision ID: c3296f6eb9ef
Revises: 0e75220aca15
Create Date: 2026-05-01 18:13:48.274475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3296f6eb9ef'
down_revision: Union[str, None] = '0e75220aca15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hocky', sa.Column('so_tuan_hoc', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hocky', 'so_tuan_hoc')
    # ### end Alembic commands ###
