"""Consolidate schedule into TKB and add AI settings

Revision ID: c7ef8c92cbc7
Revises: b02158e989a0
Create Date: 2026-05-01 17:00:54.170120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7ef8c92cbc7'
down_revision: Union[str, None] = 'b02158e989a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance_schedules')
    op.add_column('thoikhoabieu', sa.Column('ai_threshold', sa.Float(), nullable=True))
    op.add_column('thoikhoabieu', sa.Column('anti_spoofing', sa.Boolean(), nullable=True))
    op.add_column('thoikhoabieu', sa.Column('fiqa_threshold', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thoikhoabieu', 'fiqa_threshold')
    op.drop_column('thoikhoabieu', 'anti_spoofing')
    op.drop_column('thoikhoabieu', 'ai_threshold')
    op.create_table('attendance_schedules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('class_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('semester_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recurrence', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ai_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('anti_spoofing', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fiqa_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('giangvien_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['giangvien_id'], ['giangvien.id'], name=op.f('attendance_schedules_giangvien_id_fkey')),
    sa.ForeignKeyConstraint(['semester_id'], ['hocky.id'], name=op.f('attendance_schedules_semester_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('attendance_schedules_pkey'))
    )
    # ### end Alembic commands ###
