"""them_audit_trail_va_soft_delete

Revision ID: d3a64da5ef0d
Revises: 48159fee6f15
Create Date: 2026-04-11 14:18:40.001959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3a64da5ef0d'
down_revision: Union[str, None] = '48159fee6f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diemdanh', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('diemdanh', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('diemdanh', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('diemdanh', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('diemdanh', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'diemdanh', 'giangvien', ['created_by'], ['id'])
    op.create_foreign_key(None, 'diemdanh', 'giangvien', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'diemdanh', 'giangvien', ['deleted_by'], ['id'])
    op.add_column('face_embeddings', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('face_embeddings', sa.Column('trained_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'face_embeddings', 'giangvien', ['trained_by'], ['id'])
    op.add_column('giangvien', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('sinhvien', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('sinhvien', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('sinhvien', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('sinhvien', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('sinhvien', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sinhvien', 'giangvien', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'sinhvien', 'giangvien', ['created_by'], ['id'])
    op.create_foreign_key(None, 'sinhvien', 'giangvien', ['deleted_by'], ['id'])
    op.add_column('thoikhoabieu', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('thoikhoabieu', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('thoikhoabieu', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('thoikhoabieu', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('thoikhoabieu', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('thoikhoabieu', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'thoikhoabieu', 'giangvien', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'thoikhoabieu', 'giangvien', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'thoikhoabieu', 'giangvien', ['created_by'], ['id'])
    op.add_column('thongbao', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('thongbao', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('thongbao', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('thongbao', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('thongbao', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'thongbao', 'giangvien', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'thongbao', 'giangvien', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'thongbao', 'giangvien', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thongbao', type_='foreignkey')
    op.drop_constraint(None, 'thongbao', type_='foreignkey')
    op.drop_constraint(None, 'thongbao', type_='foreignkey')
    op.drop_column('thongbao', 'deleted_by')
    op.drop_column('thongbao', 'updated_by')
    op.drop_column('thongbao', 'created_by')
    op.drop_column('thongbao', 'deleted_at')
    op.drop_column('thongbao', 'updated_at')
    op.drop_constraint(None, 'thoikhoabieu', type_='foreignkey')
    op.drop_constraint(None, 'thoikhoabieu', type_='foreignkey')
    op.drop_constraint(None, 'thoikhoabieu', type_='foreignkey')
    op.drop_column('thoikhoabieu', 'deleted_by')
    op.drop_column('thoikhoabieu', 'updated_by')
    op.drop_column('thoikhoabieu', 'created_by')
    op.drop_column('thoikhoabieu', 'deleted_at')
    op.drop_column('thoikhoabieu', 'updated_at')
    op.drop_column('thoikhoabieu', 'created_at')
    op.drop_constraint(None, 'sinhvien', type_='foreignkey')
    op.drop_constraint(None, 'sinhvien', type_='foreignkey')
    op.drop_constraint(None, 'sinhvien', type_='foreignkey')
    op.drop_column('sinhvien', 'deleted_by')
    op.drop_column('sinhvien', 'updated_by')
    op.drop_column('sinhvien', 'created_by')
    op.drop_column('sinhvien', 'deleted_at')
    op.drop_column('sinhvien', 'updated_at')
    op.drop_column('giangvien', 'updated_at')
    op.drop_constraint(None, 'face_embeddings', type_='foreignkey')
    op.drop_column('face_embeddings', 'trained_by')
    op.drop_column('face_embeddings', 'updated_at')
    op.drop_constraint(None, 'diemdanh', type_='foreignkey')
    op.drop_constraint(None, 'diemdanh', type_='foreignkey')
    op.drop_constraint(None, 'diemdanh', type_='foreignkey')
    op.drop_column('diemdanh', 'deleted_by')
    op.drop_column('diemdanh', 'updated_by')
    op.drop_column('diemdanh', 'created_by')
    op.drop_column('diemdanh', 'deleted_at')
    op.drop_column('diemdanh', 'updated_at')
    # ### end Alembic commands ###
