"""Add admin columns

Revision ID: dfa28bbcb741
Revises: fcc78cd4c616
Create Date: 2026-04-29 19:39:51.812290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'dfa28bbcb741'
down_revision: Union[str, None] = 'fcc78cd4c616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('class_ids', sa.JSON(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('recurrence', sa.String(length=50), nullable=True),
    sa.Column('ai_threshold', sa.Float(), nullable=True),
    sa.Column('anti_spoofing', sa.Boolean(), nullable=True),
    sa.Column('fiqa_threshold', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['semester_id'], ['hocky.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('hocky', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('hocky', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('khoa', sa.Column('code', sa.String(), nullable=True))
    op.add_column('khoa', sa.Column('description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_khoa_code'), 'khoa', ['code'], unique=True)
    op.add_column('lop', sa.Column('code', sa.String(), nullable=True))
    op.add_column('lop', sa.Column('semester_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lop', 'hocky', ['semester_id'], ['id'])
    op.add_column('sinhvien', sa.Column('student_id', sa.String(), nullable=True))
    op.add_column('sinhvien', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('sinhvien', sa.Column('email', sa.String(), nullable=True))
    op.add_column('sinhvien', sa.Column('face_vector', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True))
    op.create_index(op.f('ix_sinhvien_email'), 'sinhvien', ['email'], unique=True)
    op.create_index(op.f('ix_sinhvien_student_id'), 'sinhvien', ['student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sinhvien_student_id'), table_name='sinhvien')
    op.drop_index(op.f('ix_sinhvien_email'), table_name='sinhvien')
    op.drop_column('sinhvien', 'face_vector')
    op.drop_column('sinhvien', 'email')
    op.drop_column('sinhvien', 'full_name')
    op.drop_column('sinhvien', 'student_id')
    op.drop_constraint(None, 'lop', type_='foreignkey')
    op.drop_column('lop', 'semester_id')
    op.drop_column('lop', 'code')
    op.drop_index(op.f('ix_khoa_code'), table_name='khoa')
    op.drop_column('khoa', 'description')
    op.drop_column('khoa', 'code')
    op.drop_column('hocky', 'end_date')
    op.drop_column('hocky', 'start_date')
    op.drop_table('attendance_schedules')
    # ### end Alembic commands ###
