"""Refactor SinhVien to use MSSV as Primary Key

Revision ID: e4331c9d7843
Revises: 27d279cf158d
Create Date: 2026-05-02 18:51:53.916050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4331c9d7843'
down_revision: Union[str, None] = '27d279cf158d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sinhvien_student_id'), table_name='sinhvien')
    op.drop_column('sinhvien', 'student_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sinhvien', sa.Column('student_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_sinhvien_student_id'), 'sinhvien', ['student_id'], unique=True)
    # ### end Alembic commands ###
