"""Add RBAC models: SystemConfig and AuditLog v2

Revision ID: fcc78cd4c616
Revises: 48bf903f43a5
Create Date: 2026-04-29 18:30:13.795614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc78cd4c616'
down_revision: Union[str, None] = '48bf903f43a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('chk_vai_tro', 'giangvien', "vai_tro IN ('giangvien', 'admin', 'super_admin')")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
